Traceback (most recent call last):
  File "/Users/arthur/miniconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/arthur/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arthur/miniconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arthur/miniconda3/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/arthur/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/arthur/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/arthur/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from transformer_lens import utils, ActivationCache, HookedTransformer, HookedTransformerConfig, FactoredMatrix
from transformer_lens.hook_points import HookPoint
from transformer_lens.components import LayerNorm
import circuitsvis as cv
import torch as t
from torchinfo import summary
from huggingface_hub import hf_hub_download
from typing import List, Optional, Tuple
from jaxtyping import Int, Float
from torch import Tensor
import plotly.express as px
import einops
import plotly.io as pio
pio.renderers.default='notebook'
# from plotly_utils import imshow, hist, plot_comp_scores, plot_logit_attribution, plot_loss_difference

t.set_grad_enabled(False)

device = t.device("cuda" if t.cuda.is_available() else "cpu")

MAIN = __name__ == "__main__"
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtransformer_lens[39;00m [38;5;28;01mimport[39;00m utils, ActivationCache, HookedTransformer, HookedTransformerConfig, FactoredMatrix
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtransformer_lens[39;00m[38;5;21;01m.[39;00m[38;5;21;01mhook_points[39;00m [38;5;28;01mimport[39;00m HookPoint
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtransformer_lens[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcomponents[39;00m [38;5;28;01mimport[39;00m LayerNorm

[0;31mModuleNotFoundError[0m: No module named 'transformer_lens'

